export default {
    translations: {
        header: {
            experience: 'Experience',
            projects: 'Projects',
            technologies: 'Technologies'
        },
        headline: {
            hi: 'Hi!',
            me: `I'm`,
            role: 'Full Stack Web Developer'
        },
        aboutMe: [
            {
                text: `I have been working as a Web Developer professionally since June 2022, and I am passionate about the field of programming!
                Since 2020, I have been studying, working on personal projects, and developing complete web applications for users and businesses.`,
                highlights: [],
                highlightStyle: {}
            },
            {
                text: `Currently, I am pursuing a postgraduate degree in Software Engineering at Unisinos (2023 - 2024).`,
                highlights: ['postgraduate', 'degree in', 'Software Engineering'],
                highlightStyle: { color: 'purple.300' }
            },
            {
                text: `The main technologies I master are .NET, Angular, and React, and I have a strong knowledge of relational databases, 
                although I also work with NoSQL.`,
                highlights: ['.NET', 'Angular', 'React'],
                highlightStyle: { color: 'purple.300' }
            },
            {
                text: `Some additional useful information about me: I'm 26 years old, I speak fluent English (or close to it), 
                I enjoy traveling, going out with my girlfriend and friends, watching sports in general (especially soccer and basketball), 
                I like watching sitcoms and Twitch streams, and I also enjoy having that daily cup (or cups) of coffee!`,
                highlights: ['useful', '(or cups)'],
                highlightStyle: { textDecoration: 'line-through', color: 'purple.300' }
            }
        ],
        technologies: {
            seeAll: 'See All'
        },
        experience: {
            sirros: {
                role: 'Full Stack Developer',
                company: 'Sirros IoT',
                period: '2022 - Present',
                description: [
                    `Development and maintenance of robust and scalable web applications, primarily using .NET, Angular, and Angularjs technologies.`,
                    `Implementation of Background Services in .NET for utilizing queue/messaging services with Azure Service Bus, 
                    websockets with SignalR, among others.`
                ]
            }
        },
        projects: {
            psiCalendar: {
                name: 'PsiCalendar',
                period: '2022 - Present',
                tags : ['.NET', 'React', 'Next.js', 'Chakra UI', 'MySQL', 'EF Core', 'Docker', 'Vercel'],
                description: [
                    `PsiCalendar is a web application designed for professionals working in the field of clinical psychology. 
                    It offers an effective way to manage all aspects of the business, from appointment scheduling to financial tracking.`,
            
                    `Professionals can easily schedule and track appointments, view an intuitive weekly calendar, generate progress notes for patients,
                     and create payment receipts. Additionally, the application provides a comprehensive overview of no-shows, payments, 
                     and outstanding balances, enabling professionals to maintain precise control over their clinical practices.
                    `,
            
                    `The application was primarily developed using the technologies listed below and is currently in use by professionals in the field.
                    `
               ],
            },
            comparer: {
                name: 'Comparator',
                period: '2023',
                tags : ['.NET', 'React', 'Electron', 'Windows Services', 'Chakra UI', 'ExcelJS'],
                description: [
                    `The Comparator was custom-developed to meet the specific needs of an accounting firm. 
                    The application imports files generated by another accounting system and, by reading these files, 
                    allows the application of various customizable filters according to the users' needs.`,
            
                    `Furthermore, the application provides the flexibility to generate reports in spreadsheet format or directly in PDF.
                    `,
            
                    `To ensure the application could be used on the desktop and still have a user-friendly interface, 
                    Electron was used for the front-end, and the back-end functions as a Windows service.
                    `
               ],
            }
        }

    }
}